### ISSUE TITLE
Import fails on Windows

### ISSUE THREAD

**Issue by d3dave** [revng/llvmcpy#12]
On Windows, [this line](https://github.com/revng/llvmcpy/blob/master/llvmcpy/llvm.py#L675) fails due to the missing `HOME` and `XDG_CACHE_DIR` environment vars.

**Comment by aleclearmind** [comment]
I guess we should use [os.path.expanduser](https://docs.python.org/3/library/os.path.html#os.path.expanduser). Would you mind providing a patch?

**Comment by d3dave** [comment]
Well, that's one option. We probably should use the `LOCALAPPDATA` environment variable as evidenced by:
1. [This wikipedia section](https://en.wikipedia.org/wiki/Environment_variable#Windows), and
2. [This issue for electron](https://github.com/electron/electron/issues/1404). You can also see ~4-5 references to that issue from other projects.

**Comment by aleclearmind** [comment]
We should probably use [appdirs](https://pypi.python.org/pypi/appdirs/1.4.3). Can you make a patch for this?

Thanks.
