### ISSUE TITLE
global name 'llvm' is not defined

### ISSUE THREAD

**Issue by techvoltage** [revng/llvmcpy#13]
On Ubuntu 16.04, running 'python llvmcpy/test.py' gives this error after I run sudo pip install llvmcpy and sudo apt-get install llvm

**Comment by aleclearmind** [comment]
I can't reproduce, can you please report the version of Python and LLVM you're using?
Can you try to uninstall and reinstall the package and clean the cache (`~/.cache/llvmcpy`)?

Thanks.
