### ISSUE TITLE
NULL cffi values should be represented as None

### ISSUE THREAD

**Issue by yurivict** [revng/llvmcpy#15]
I have the object ```llConstant``` that is the LLVM value of the argument of the ```Call``` instruction.

Such value can be an instruction, or a function, or some other static constant.

Once it is a constant, there is trouble differentiating between function and LLVM static constant.

This statement:
```
print("str(llConstant.is_a_function())+" in_ptr="+str(llConstant.is_a_function().in_ptr())+" type="+str(type(llConstant.is_a_function().in_ptr())))
```
prints either
```
<llvmcpyimpl.Value object at 0x80f0faf10> in_ptr=<cdata 'struct LLVMOpaqueValue *' 0x805549808> type=<type '_cffi_backend.CData'>
```
or
```
<llvmcpyimpl.Value object at 0x80f0faf50> in_ptr=<cdata 'struct LLVMOpaqueValue *' NULL> type=<type '_cffi_backend.CData'>
```

```llConstant.is_a_function() is None``` always returns ```False```.

The underlying ```NULL``` values should be translated into the Python's ```None``` object.
Otherwise it's  hard or impossible to determine that it is NULL. And users should never need to fish out pointers of native objects.

This is a show-stopper bug, because in the current form one can't do advanced things with the library.

**Comment by yurivict** [comment]
@d3dave Sorry for bugging you, but you were the last committer.
Maybe you can fix this?

**Comment by aleclearmind** [comment]
Are you sure you're using the latest version? The constructor of the classes returns `None` if the pointer is `ffi.NULL` (see 679d2c1746a02c39806a957f8a7c69d672a05a14).

I've quickly tested it and it seems to work:

```
In [15]: func.is_a_alloca_inst() is None
Out[15]: True

In [16]: func.is_a_function() is None
Out[16]: False
```

**Comment by yurivict** [comment]
I was using the older version of py-cffi.
Now, with the new version, the problem is gone.

I apologize for bothering you!

**Comment by aleclearmind** [comment]
Great!
