### ISSUE TITLE
[feature request] Please add a way to enumerate LLVM instructions

### ISSUE THREAD

**Issue by yurivict** [revng/llvmcpy#16]
All instructions are in the ```llvm.*``` namespace, but the user might desire to have a list of instructions, to translate opcode id to name. This should be supported.

**Comment by aleclearmind** [comment]
Is `llvm.Opcode` what you're looking for?

```
In [17]: llvm.Opcode
Out[17]: 
{1: 'Ret',
 2: 'Br',
 3: 'Switch',
 4: 'IndirectBr',
 5: 'Invoke',
 7: 'Unreachable',
 ...
 'AShr': 22,
 'Add': 8,
 'AddrSpaceCast': 60,
 'Alloca': 26,
 ...}
```

**Comment by yurivict** [comment]
Revision  6635c3a  doesn't have ```Opcode```:
```
>>> import llvmcpy
>>> llvm.Opcode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'llvm' is not defined
```

Using llvm-39 on FreeBSD 11.1

**Comment by yurivict** [comment]
Revision 6635c3a doesn't have ```Opcode```:

```
>>> from llvmcpy import llvm
>>> llvm.Opcode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Opcode'
```

**Comment by aleclearmind** [comment]
Yes, I am.

* Can you try to clean the cache and retry?

  ```
  rm -rf  ~/.cache/llvmcpy/
  ```

* What LLVM version are you using?
* Can you attach `include/llvm-c/Core.h`? Does it contain the `LLVMOpcode` `enum`?

**Comment by yurivict** [comment]
I am using llvm-39 and llvm-40.

It does work, but I am also getting the intermittent errors. When I created this report I was only getting errors.

I will be trying to identify what causes them.

**Comment by yurivict** [comment]
Ok, I will close this bug.
I am not sure why I was seeing the errors.
