### ISSUE TITLE
Process is exited if C preprocessor is missing

### ISSUE THREAD

**Issue by d3dave** [revng/llvmcpy#20]
If a C preprocessor is not found, the process is `exit`ed instead of raising an appropriate exception for handling.

The culprit is line 402.

**Comment by aleclearmind** [comment]
Right, I'm used to use `assert` a lot. Can you provide a patch?

**Comment by aleclearmind** [comment]
Closed with 1306b3c553455309ef37815d6ab1dfd771434c63
