### ISSUE TITLE
File not found all.prep.c in OSX High Sierra

### ISSUE THREAD

**Issue by elefthei** [revng/llvmcpy#22]
```
>>> from llvmcpy import llvm
.
.
.

void LLVMAddPruneEHPass(LLVMPassManagerRef PM);


void LLVMAddIPSCCPPass(LLVMPassManagerRef PM);


void LLVMAddInternalizePass(LLVMPassManagerRef, unsigned AllButMain);


void LLVMAddStripDeadPrototypesPass(LLVMPassManagerRef PM);


void LLVMAddStripSymbolsPass(LLVMPassManagerRef PM);










# 25 "/var/folders/hz/8nnwxpvn4b9b_b6_xj_czfb00000gn/T/tmpPSxATs/all.c" 2

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lef/git/hybridverif/env/lib/python2.7/site-packages/llvmcpy/llvm.py", line 605, in <module>
    generate_wrapper()
  File "/Users/lef/git/hybridverif/env/lib/python2.7/site-packages/llvmcpy/llvm.py", line 467, in generate_wrapper
    libs, ffi_code = parse_headers()
  File "/Users/lef/git/hybridverif/env/lib/python2.7/site-packages/llvmcpy/llvm.py", line 434, in parse_headers
    ffi.cdef(open(all_c_preprocessed).read(), override=True)
IOError: [Errno 2] No such file or directory: '/var/folders/hz/8nnwxpvn4b9b_b6_xj_czfb00000gn/T/tmpPSxATs/all.prep.c'
```

Some header files are seem to be found, just not `all.c` or `all.prep.c`. Error reproduces both as root, as virtual env and as normal user.

**Comment by aleclearmind** [comment]
Sorry but I don't have a macOS installation at my disposal, you'll have to help me out here.

First of all, can you attach the *complete* output of `python -c 'from llvmcpy import llvm`? There might be an error with the preprocessor but [subprocess.check_call](https://docs.python.org/2/library/subprocess.html#subprocess.check_call) should give an error in that case...

An hypothesis is that the `-o` option is, for some reason, ignored and therefore everything works properly except for the fact that the preprocessor output goes to `stdout` and not to `all.prep.c`.
Can you prepend to `check_call` a `print` of its arguments and paste it here?

Thanks for reporting this!

**Comment by elefthei** [comment]
Found the issue see https://github.com/revng/llvmcpy/pull/23
Now I'm getting a

```
ValueError: No valid LLVM libraries found'             ', LLVM must be built with BUILD_SHARED_LIBS
```

But this might be something with how I built my llvm.

**Comment by aleclearmind** [comment]
Can you please see if e50f550cf50670fbd86f74aee285d23c65ee3b0a (branch `feature/better-program-search`) fixes the issue?

**Comment by elefthei** [comment]
Seems to work, thanks!
