### ISSUE TITLE
PyPi release not working on Python 3

### ISSUE THREAD

**Issue by mafrasi2** [revng/llvmcpy#24]
The current version on PyPi still doesn't work on Python 3 even though the issue has been fixed [more than a year ago](https://github.com/revng/llvmcpy/issues/2).

**Comment by aleclearmind** [comment]
Sorry for the huge delay. llvmcpy 0.1.2 has been released and published on [pypi](https://pypi.python.org/pypi/llvmcpy/0.1.2).
Thanks for the reminder.
